#define BUTTON_COUNT 4
#define BROADCAST_INTERVAL 1000
#define DEAD_COMMS_INTERVAL 10000
#define DEBOUNCE_TIME 20

#define PIN_LED_STRIP 23
#define STRIP_BRIGHTNESS 255
#define STRIP_BRIGHTNESS_DIM 30

#define MAX_PACKET_DATA_LENGTH 32
#define RADIO_BROADCAST_ADDRESS 0xFFFF

#define HEALTH_LED 13
#define BUZZER_PIN 16


// Button Pins
#define PIN_BLACK 19
#define PIN_RED 20
#define PIN_BLUE 21
#define PIN_YELLOW 22